<?php
/**
 * ApiKeysApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  InvoicePDFs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace InvoicePDFs\Test\Api;

use \InvoicePDFs\Configuration;
use \InvoicePDFs\ApiException;
use \InvoicePDFs\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApiKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  InvoicePDFs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApiKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createApiKey
     *
     * Create Api Key.
     *
     */
    public function testCreateApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiKey
     *
     * Get Api Key.
     *
     */
    public function testGetApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApiKeys
     *
     * List Api Keys.
     *
     */
    public function testListApiKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeApiKey
     *
     * Revoke Api Key.
     *
     */
    public function testRevokeApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rotateApiKey
     *
     * Rotate Api Key.
     *
     */
    public function testRotateApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateApiKey
     *
     * Update Api Key.
     *
     */
    public function testUpdateApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
